apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::412381735865:user/hybrid-cloud-app
      username: hybrid-cloud-app
      groups:
        - system:masters
